tab_spaces = 2
max_width = 120
newline_style = "unix"

unstable_features = true
fn_single_line = true
imports_granularity = "Crate"
brace_style = "PreferSameLine"
wrap_comments = true
where_single_line = true